<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Linea', 'doctrine');

/**
 * BaseLinea
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $descripcion
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property integer $created_by
 * @property integer $updated_by
 * @property Marca $Marca
 * @property Doctrine_Collection $Unidad
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method string              getDescripcion() Returns the current record's "descripcion" value
 * @method timestamp           getCreatedAt()   Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()   Returns the current record's "updated_at" value
 * @method integer             getCreatedBy()   Returns the current record's "created_by" value
 * @method integer             getUpdatedBy()   Returns the current record's "updated_by" value
 * @method Marca               getMarca()       Returns the current record's "Marca" value
 * @method Doctrine_Collection getUnidad()      Returns the current record's "Unidad" collection
 * @method Linea               setId()          Sets the current record's "id" value
 * @method Linea               setDescripcion() Sets the current record's "descripcion" value
 * @method Linea               setCreatedAt()   Sets the current record's "created_at" value
 * @method Linea               setUpdatedAt()   Sets the current record's "updated_at" value
 * @method Linea               setCreatedBy()   Sets the current record's "created_by" value
 * @method Linea               setUpdatedBy()   Sets the current record's "updated_by" value
 * @method Linea               setMarca()       Sets the current record's "Marca" value
 * @method Linea               setUnidad()      Sets the current record's "Unidad" collection
 * 
 * @package    sistem-taxi
 * @subpackage model
 * @author     Walter Rosales
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLinea extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('linea');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('descripcion', 'string', 85, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 85,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('created_by', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('updated_by', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Marca', array(
             'local' => 'id',
             'foreign' => 'id'));

        $this->hasMany('Unidad', array(
             'local' => 'id',
             'foreign' => 'linea_id'));
    }
}