<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Township', 'doctrine');

/**
 * BaseTownship
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $state_id
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property State $State
 * @property Doctrine_Collection $ConstructionOrder
 * @property Doctrine_Collection $ConstructorTownship
 * 
 * @method integer             getId()                  Returns the current record's "id" value
 * @method string              getName()                Returns the current record's "name" value
 * @method integer             getStateId()             Returns the current record's "state_id" value
 * @method timestamp           getCreatedAt()           Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()           Returns the current record's "updated_at" value
 * @method State               getState()               Returns the current record's "State" value
 * @method Doctrine_Collection getConstructionOrder()   Returns the current record's "ConstructionOrder" collection
 * @method Doctrine_Collection getConstructorTownship() Returns the current record's "ConstructorTownship" collection
 * @method Township            setId()                  Sets the current record's "id" value
 * @method Township            setName()                Sets the current record's "name" value
 * @method Township            setStateId()             Sets the current record's "state_id" value
 * @method Township            setCreatedAt()           Sets the current record's "created_at" value
 * @method Township            setUpdatedAt()           Sets the current record's "updated_at" value
 * @method Township            setState()               Sets the current record's "State" value
 * @method Township            setConstructionOrder()   Sets the current record's "ConstructionOrder" collection
 * @method Township            setConstructorTownship() Sets the current record's "ConstructorTownship" collection
 * 
 * @package    sistem-taxi
 * @subpackage model
 * @author     Walter Rosales
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTownship extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('township');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 8,
             ));
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));
        $this->hasColumn('state_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('State', array(
             'local' => 'state_id',
             'foreign' => 'id'));

        $this->hasMany('ConstructionOrder', array(
             'local' => 'id',
             'foreign' => 'township_id'));

        $this->hasMany('ConstructorTownship', array(
             'local' => 'id',
             'foreign' => 'township_id'));
    }
}