<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('rutaServicio', 'doctrine');

/**
 * BaseLinea
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $servicio_id
 * @property integer $unidad_id
 * @property string  $ruta
 * @property timestamp $fecha
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method integer             getServicioId()  Returns the current record's "servicio_id" value
 * @method integer             getUnidadId()    Returns the current record's "unidad_id" value
 * @method string              getRuta()        Returns the current record's "ruta" value
 * @method timestamp           getFecha()       Returns the current record's "fecha" value
 * @method rutaServicio        setId()          Sets the current record's "id" value
 * @method rutaServicio        setServicioId()  Sets the current record's "servicio_id" value
 * @method rutaServicio        setUnidadId()    Sets the current record's "unidad_id" value
 * @method rutaServicio        setRuta()        Sets the current record's "ruta" value
 * @method rutaServicio        setFecha()       Sets the current record's "fecha" value
 * 
 * @package    sistem-taxi
 * @subpackage model
 * @author     Walter Rosales
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRutaServicio extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ruta_servicio');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('servicio_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' =>4,
             ));
        $this->hasColumn('unidad_id', 'integer', 4, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('ruta', 'string', 1000, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 1000,
             ));
        $this->hasColumn('fecha', 'timestamp', 25, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        
       
    }
}