<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('RespuestaTs', 'doctrine');

/**
 * BaseRespuestaTs
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $respuesta
 * @property integer $mensaje_id
 * @property integer $user_id
 * @property integer $type
 * @property timestamp $fecha
 * 
 * @method integer     getId()         Returns the current record's "id" value
 * @method string      getRespuesta()  Returns the current record's "respuesta" value
 * @method integer     getMensajeId()  Returns the current record's "mensaje_id" value
 * @method integer     getUserId()     Returns the current record's "user_id" value
 * @method integer     getType()       Returns the current record's "type" value
 * @method timestamp   getFecha()      Returns the current record's "fecha" value
 * @method RespuestaTs setId()         Sets the current record's "id" value
 * @method RespuestaTs setRespuesta()  Sets the current record's "respuesta" value
 * @method RespuestaTs setMensajeId()  Sets the current record's "mensaje_id" value
 * @method RespuestaTs setUserId()     Sets the current record's "user_id" value
 * @method RespuestaTs setType()       Sets the current record's "type" value
 * @method RespuestaTs setFecha()      Sets the current record's "fecha" value
 * 
 * @package    sistem-taxi
 * @subpackage model
 * @author     Walter Rosales
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRespuestaTs extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('respuesta_ts');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('respuesta', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
        $this->hasColumn('mensaje_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('type', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('fecha', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}