<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Mensaje', 'doctrine');

/**
 * BaseMensaje
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $contendio
 * @property integer $tipo
 * @property integer $predeterminada
 * @property integer $respuesta
 * @property integer $id_usuario
 * 
 * @method integer getId()             Returns the current record's "id" value
 * @method string  getContendio()      Returns the current record's "contendio" value
 * @method integer getTipo()           Returns the current record's "tipo" value
 * @method integer getPredeterminada() Returns the current record's "predeterminada" value
 * @method integer getRespuesta()      Returns the current record's "respuesta" value
 * @method integer getIdUsuario()      Returns the current record's "id_usuario" value
 * @method Mensaje setId()             Sets the current record's "id" value
 * @method Mensaje setContendio()      Sets the current record's "contendio" value
 * @method Mensaje setTipo()           Sets the current record's "tipo" value
 * @method Mensaje setPredeterminada() Sets the current record's "predeterminada" value
 * @method Mensaje setRespuesta()      Sets the current record's "respuesta" value
 * @method Mensaje setIdUsuario()      Sets the current record's "id_usuario" value
 * 
 * @package    sistem-taxi
 * @subpackage model
 * @author     Walter Rosales
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMensaje extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mensaje');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('contendio', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('tipo', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '2',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('predeterminada', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('respuesta', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_usuario', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}