<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Anio', 'doctrine');

/**
 * BaseAnio
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $description
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property integer $created_by
 * @property integer $update_byt
 * @property Doctrine_Collection $Unidad
 * 
 * @method integer             getId()          Returns the current record's "id" value
 * @method integer             getDescription() Returns the current record's "description" value
 * @method timestamp           getCreatedAt()   Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()   Returns the current record's "updated_at" value
 * @method integer             getCreatedBy()   Returns the current record's "created_by" value
 * @method integer             getUpdateByt()   Returns the current record's "update_byt" value
 * @method Doctrine_Collection getUnidad()      Returns the current record's "Unidad" collection
 * @method Anio                setId()          Sets the current record's "id" value
 * @method Anio                setDescription() Sets the current record's "description" value
 * @method Anio                setCreatedAt()   Sets the current record's "created_at" value
 * @method Anio                setUpdatedAt()   Sets the current record's "updated_at" value
 * @method Anio                setCreatedBy()   Sets the current record's "created_by" value
 * @method Anio                setUpdateByt()   Sets the current record's "update_byt" value
 * @method Anio                setUnidad()      Sets the current record's "Unidad" collection
 * 
 * @package    sistem-taxi
 * @subpackage model
 * @author     Walter Rosales
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAnio extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('anio');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('description', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('created_by', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('update_byt', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Unidad', array(
             'local' => 'id',
             'foreign' => 'anio_id'));
    }
}