<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Chat', 'doctrine');

/**
 * BaseChat
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property string $msg
 * @property string $timestamp
 * @property string $displayed
 * 
 * @method integer getId()        Returns the current record's "id" value
 * @method integer getUserId()    Returns the current record's "user_id" value
 * @method string  getMsg()       Returns the current record's "msg" value
 * @method string  getTimestamp() Returns the current record's "timestamp" value
 * @method string  getDisplayed() Returns the current record's "displayed" value
 * @method Chat    setId()        Sets the current record's "id" value
 * @method Chat    setUserId()    Sets the current record's "user_id" value
 * @method Chat    setMsg()       Sets the current record's "msg" value
 * @method Chat    setTimestamp() Sets the current record's "timestamp" value
 * @method Chat    setDisplayed() Sets the current record's "displayed" value
 * 
 * @package    sistem-taxi
 * @subpackage model
 * @author     Walter Rosales
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseChat extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('chat');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             'length' => 8,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('msg', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('timestamp', 'string', 250, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 250,
             ));
        $this->hasColumn('displayed', 'string', 1, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 1,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}