<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CategoriaCliente', 'doctrine');

/**
 * BaseCategoriaCliente
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $descripcion
 * 
 * @method integer          getId()          Returns the current record's "id" value
 * @method string           getDescripcion() Returns the current record's "descripcion" value
 * @method CategoriaCliente setId()          Sets the current record's "id" value
 * @method CategoriaCliente setDescripcion() Sets the current record's "descripcion" value
 * 
 * @package    sistem-taxi
 * @subpackage model
 * @author     Walter Rosales
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCategoriaCliente extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('categoria_cliente');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}