# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    title:         Sistema Mi Taxi Seguro
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [stye.css,jquery-ui-1.7.3.custom.css,alertify.core.css,alertify.default.css,jquery.fancybox.css,jquery.fancybox-buttons.css?v=1.0.5,jquery.dataTables.css]

  javascripts:    [jquery.fancybox.css?v=2.1.5,alertify.js,jquery-1.3.2.min.js,jquery-1.10.2.min.js,ajax_mt.js,jquery.mousewheel-3.0.6.pack.js,jquery.fancybox.pack.js?v=2.1.5,jquery.dataTables.min.js]

  has_layout:     true
  layout:         layout
