<?php

/**
 * AnioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AnioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AnioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Anio');
    }
}