<?php

/**
 * AsignacionUnidadPilotoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AsignacionUnidadPilotoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AsignacionUnidadPilotoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AsignacionUnidadPiloto');
    }
     public function namepiloto($id){

    	$piloto = Doctrine::getTable('piloto')->find($id);
    	return $piloto[0]->getFirstName();

    }
	 
	
	 
}