<?php

/**
 * CategoriaClienteTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoriaClienteTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoriaClienteTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CategoriaCliente');
    }
}