<?php

/**
 * ChatUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ChatUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ChatUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ChatUser');
    }
}