<?php

/**
 * ColaboradorTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ColaboradorTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ColaboradorTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Colaborador');
    }
}