<?php

/**
 * EmpresaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EmpresaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EmpresaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Empresa');
    }
}