<?php

/**
 * HoraPicoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class HoraPicoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object HoraPicoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('HoraPico');
    }
}