<?php

/**
 * LineaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LineaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LineaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Linea');
    }
}