<?php

/**
 * MapsStatesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MapsStatesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MapsStatesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MapsStates');
    }
}