<?php

/**
 * ReservacionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ReservacionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ReservacionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Reservacion');
    }
}