<?php

/**
 * RespuestaTsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RespuestaTsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RespuestaTsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RespuestaTs');
    }
}