<?php

/**
 * SmiliesTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SmiliesTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SmiliesTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Smilies');
    }
}