<?php

/**
 * TarifaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TarifaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TarifaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Tarifa');
    }
	
	public function obtenerTarifa($id){
		
		
		//$q = Doctrine::getTable('Tarifa')->findById($id);
		////echo $q[0]->getMonto();
	}
}