<?php

/**
 * TrafiaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrafiaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrafiaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Trafia');
    }
}