<?php

/**
 * Unidad
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sistem-taxi
 * @subpackage model
 * @author     Walter Rosales
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Unidad extends BaseUnidad
{
	public function obtenerpiloto($unidadid){
		
		$q = Doctrine::getTable('asignacionUnidadPiloto')->findByUnidadId($unidadid);
		$t = Doctrine::getTable('piloto')->findById($q[0]['id_piloto']);
		echo $t[0]['first_name']." ".$t[0]['last_name'];
	}
	 
}
