<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/11/25 00:48:00

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=db461977375.db.1and1.com;dbname=db461977375',
  'username' => 'dbo461977375',
  'password' => 'locames2013',
  'name' => 'doctrine',
)),);
