<?php
// auto-generated by sfSecurityConfigHandler
// date: 2015/11/25 08:50:42
$this->security = array (
  'homepage' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 'admin',
      1 => 'permisosBasicos',
    ),
  ),
  'user' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 'admin',
    ),
  ),
  'secure' => 
  array (
    'is_secure' => false,
  ),
  'signin' => 
  array (
    'is_secure' => false,
  ),
  'signout' => 
  array (
    'is_secure' => false,
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
