<?php
// auto-generated by sfSecurityConfigHandler
// date: 2015/12/17 14:52:13
$this->security = array (
  'homepage' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 'admin',
      1 => 'permisosBasicos',
    ),
  ),
  'user' => 
  array (
    'is_secure' => true,
    'credentials' => 
    array (
      0 => 'admin',
    ),
  ),
  'all' => 
  array (
    'is_secure' => true,
  ),
);
