<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2015/11/25 00:48:00
sfConfig::add(array(
  'mod_ruta_corporativa_enabled' => true,
  'mod_ruta_corporativa_view_class' => 'sfPHP',
));
