<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2015/12/17 13:44:44
sfConfig::add(array(
  'mod_unidad_no_reportada_enabled' => true,
  'mod_unidad_no_reportada_view_class' => 'sfPHP',
));
