generator:
  class: sfDoctrineGenerator
  param:
    model_class:           piloto
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          piloto
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: Lista de Pilotos
        hide: [created_at,updated_at,created_by,email,licencia,dpi,cedula]
        max_per_page: 10
      filter:
        class: false
      form:    ~
      edit:
        title: Modificar Piloto
      new:
        title: Nuevo Piloto
