<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ChatUser', 'doctrine');

/**
 * BaseChatUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $user_id
 * @property integer $operador_id
 * @property integer $status
 * @property timestamp $created_at
 * 
 * @method integer   getId()          Returns the current record's "id" value
 * @method integer   getUserId()      Returns the current record's "user_id" value
 * @method integer   getOperadorId()  Returns the current record's "operador_id" value
 * @method integer   getStatus()      Returns the current record's "status" value
 * @method timestamp getCreatedAt()   Returns the current record's "created_at" value
 * @method ChatUser  setId()          Sets the current record's "id" value
 * @method ChatUser  setUserId()      Sets the current record's "user_id" value
 * @method ChatUser  setOperadorId()  Sets the current record's "operador_id" value
 * @method ChatUser  setStatus()      Sets the current record's "status" value
 * @method ChatUser  setCreatedAt()   Sets the current record's "created_at" value
 * 
 * @package    sistem-taxi
 * @subpackage model
 * @author     Walter Rosales
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseChatUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('chat_user');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('user_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('operador_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('status', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'default' => '0',
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}