<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('ClientChat', 'doctrine');

/**
 * BaseClientChat
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $nickname
 * @property timestamp $created_at
 * 
 * @method integer    getId()         Returns the current record's "id" value
 * @method string     getNickname()   Returns the current record's "nickname" value
 * @method timestamp  getCreatedAt()  Returns the current record's "created_at" value
 * @method ClientChat setId()         Sets the current record's "id" value
 * @method ClientChat setNickname()   Sets the current record's "nickname" value
 * @method ClientChat setCreatedAt()  Sets the current record's "created_at" value
 * 
 * @package    sistem-taxi
 * @subpackage model
 * @author     Walter Rosales
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseClientChat extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('client_chat');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('nickname', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}