<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Respuesta', 'doctrine');

/**
 * BaseRespuesta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $mensaje_id
 * @property string $respuesta
 * 
 * @method integer   getId()         Returns the current record's "id" value
 * @method integer   getMensajeId()  Returns the current record's "mensaje_id" value
 * @method string    getRespuesta()  Returns the current record's "respuesta" value
 * @method Respuesta setId()         Sets the current record's "id" value
 * @method Respuesta setMensajeId()  Sets the current record's "mensaje_id" value
 * @method Respuesta setRespuesta()  Sets the current record's "respuesta" value
 * 
 * @package    sistem-taxi
 * @subpackage model
 * @author     Walter Rosales
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseRespuesta extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('respuesta');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('mensaje_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('respuesta', 'string', 200, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 200,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}