<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('EnvioUnidad', 'doctrine');

/**
 * BaseEnvioUnidad
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $unidad_id
 * @property integer $servicio_id
 * @property integer $estado
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property integer $created_by
 * @property integer $updated_by
 * 
 * @method integer     getId()          Returns the current record's "id" value
 * @method integer     getUnidadId()    Returns the current record's "unidad_id" value
 * @method integer     getServicioId()  Returns the current record's "servicio_id" value
 * @method integer     getEstado()      Returns the current record's "estado" value
 * @method timestamp   getCreatedAt()   Returns the current record's "created_at" value
 * @method timestamp   getUpdatedAt()   Returns the current record's "updated_at" value
 * @method integer     getCreatedBy()   Returns the current record's "created_by" value
 * @method integer     getUpdatedBy()   Returns the current record's "updated_by" value
 * @method EnvioUnidad setId()          Sets the current record's "id" value
 * @method EnvioUnidad setUnidadId()    Sets the current record's "unidad_id" value
 * @method EnvioUnidad setServicioId()  Sets the current record's "servicio_id" value
 * @method EnvioUnidad setEstado()      Sets the current record's "estado" value
 * @method EnvioUnidad setCreatedAt()   Sets the current record's "created_at" value
 * @method EnvioUnidad setUpdatedAt()   Sets the current record's "updated_at" value
 * @method EnvioUnidad setCreatedBy()   Sets the current record's "created_by" value
 * @method EnvioUnidad setUpdatedBy()   Sets the current record's "updated_by" value
 * 
 * @package    sistem-taxi
 * @subpackage model
 * @author     Walter Rosales
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEnvioUnidad extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('envio_unidad');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('unidad_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('servicio_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('estado', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('created_by', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('updated_by', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}