<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('CtrlCredit', 'doctrine');

/**
 * BaseCtrlCredit
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $constructor_order_id
 * @property integer $status
 * @property integer $bank_id
 * @property ConstructorOrder $ConstructorOrder
 * @property Bank $Bank
 * 
 * @method integer          getId()                   Returns the current record's "id" value
 * @method integer          getConstructorOrderId()   Returns the current record's "constructor_order_id" value
 * @method integer          getStatus()               Returns the current record's "status" value
 * @method integer          getBankId()               Returns the current record's "bank_id" value
 * @method ConstructorOrder getConstructorOrder()     Returns the current record's "ConstructorOrder" value
 * @method Bank             getBank()                 Returns the current record's "Bank" value
 * @method CtrlCredit       setId()                   Sets the current record's "id" value
 * @method CtrlCredit       setConstructorOrderId()   Sets the current record's "constructor_order_id" value
 * @method CtrlCredit       setStatus()               Sets the current record's "status" value
 * @method CtrlCredit       setBankId()               Sets the current record's "bank_id" value
 * @method CtrlCredit       setConstructorOrder()     Sets the current record's "ConstructorOrder" value
 * @method CtrlCredit       setBank()                 Sets the current record's "Bank" value
 * 
 * @package    sistem-taxi
 * @subpackage model
 * @author     Walter Rosales
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCtrlCredit extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ctrl_credit');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('constructor_order_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 8,
             ));
        $this->hasColumn('status', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('bank_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ConstructorOrder', array(
             'local' => 'constructor_order_id',
             'foreign' => 'id'));

        $this->hasOne('Bank', array(
             'local' => 'bank_id',
             'foreign' => 'id'));
    }
}