<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Viaje', 'doctrine');

/**
 * BaseViaje
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $descripcion
 * @property integer $mensaje_unidad_id
 * @property timestamp $created_at
 * @property timestamp $update_at
 * @property integer $created_by
 * @property integer $updated_by
 * @property UnidadMensaje $UnidadMensaje
 * 
 * @method integer       getId()                Returns the current record's "id" value
 * @method string        getDescripcion()       Returns the current record's "descripcion" value
 * @method integer       getMensajeUnidadId()   Returns the current record's "mensaje_unidad_id" value
 * @method timestamp     getCreatedAt()         Returns the current record's "created_at" value
 * @method timestamp     getUpdateAt()          Returns the current record's "update_at" value
 * @method integer       getCreatedBy()         Returns the current record's "created_by" value
 * @method integer       getUpdatedBy()         Returns the current record's "updated_by" value
 * @method UnidadMensaje getUnidadMensaje()     Returns the current record's "UnidadMensaje" value
 * @method Viaje         setId()                Sets the current record's "id" value
 * @method Viaje         setDescripcion()       Sets the current record's "descripcion" value
 * @method Viaje         setMensajeUnidadId()   Sets the current record's "mensaje_unidad_id" value
 * @method Viaje         setCreatedAt()         Sets the current record's "created_at" value
 * @method Viaje         setUpdateAt()          Sets the current record's "update_at" value
 * @method Viaje         setCreatedBy()         Sets the current record's "created_by" value
 * @method Viaje         setUpdatedBy()         Sets the current record's "updated_by" value
 * @method Viaje         setUnidadMensaje()     Sets the current record's "UnidadMensaje" value
 * 
 * @package    sistem-taxi
 * @subpackage model
 * @author     Walter Rosales
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseViaje extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('viaje');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('mensaje_unidad_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('update_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('created_by', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('updated_by', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('UnidadMensaje', array(
             'local' => 'mensaje_unidad_id',
             'foreign' => 'id'));
    }
}