<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Cliente', 'doctrine');

/**
 * BaseCliente
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $first_name
 * @property string $last_name
 * @property timestamp $fecha_nacimiento
 * @property enum $genero
 * @property string $direccion
 * @property integer $telefono
 * @property integer $celular
 * @property string $identificacion
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property integer $created_by
 * @property integer $updated_by
 * @property Doctrine_Collection $Reservacion
 * 
 * @method integer             getId()               Returns the current record's "id" value
 * @method string              getFirstName()        Returns the current record's "first_name" value
 * @method string              getLastName()         Returns the current record's "last_name" value
 * @method timestamp           getFechaNacimiento()  Returns the current record's "fecha_nacimiento" value
 * @method enum                getGenero()           Returns the current record's "genero" value
 * @method string              getDireccion()        Returns the current record's "direccion" value
 * @method integer             getTelefono()         Returns the current record's "telefono" value
 * @method integer             getCelular()          Returns the current record's "celular" value
 * @method string              getIdentificacion()   Returns the current record's "identificacion" value
 * @method timestamp           getCreatedAt()        Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()        Returns the current record's "updated_at" value
 * @method integer             getCreatedBy()        Returns the current record's "created_by" value
 * @method integer             getUpdatedBy()        Returns the current record's "updated_by" value
 * @method Doctrine_Collection getReservacion()      Returns the current record's "Reservacion" collection
 * @method Cliente             setId()               Sets the current record's "id" value
 * @method Cliente             setFirstName()        Sets the current record's "first_name" value
 * @method Cliente             setLastName()         Sets the current record's "last_name" value
 * @method Cliente             setFechaNacimiento()  Sets the current record's "fecha_nacimiento" value
 * @method Cliente             setGenero()           Sets the current record's "genero" value
 * @method Cliente             setDireccion()        Sets the current record's "direccion" value
 * @method Cliente             setTelefono()         Sets the current record's "telefono" value
 * @method Cliente             setCelular()          Sets the current record's "celular" value
 * @method Cliente             setIdentificacion()   Sets the current record's "identificacion" value
 * @method Cliente             setCreatedAt()        Sets the current record's "created_at" value
 * @method Cliente             setUpdatedAt()        Sets the current record's "updated_at" value
 * @method Cliente             setCreatedBy()        Sets the current record's "created_by" value
 * @method Cliente             setUpdatedBy()        Sets the current record's "updated_by" value
 * @method Cliente             setReservacion()      Sets the current record's "Reservacion" collection
 * 
 * @package    sistem-taxi
 * @subpackage model
 * @author     Walter Rosales
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCliente extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cliente');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('first_name', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('last_name', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('fecha_nacimiento', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('genero', 'enum', 9, array(
             'type' => 'enum',
             'fixed' => 0,
             'unsigned' => false,
             'values' => 
             array(
              0 => 'Masculino',
              1 => 'Femenino',
             ),
             'primary' => false,
             'default' => 'Masculino',
             'notnull' => false,
             'autoincrement' => false,
             'length' => 9,
             ));
        $this->hasColumn('direccion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('telefono', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('celular', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('identificacion', 'string', 20, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 20,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('created_by', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('updated_by', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Reservacion', array(
             'local' => 'id',
             'foreign' => 'client_id'));
    }
}