<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('MensajeUnidadtablet', 'doctrine');

/**
 * BaseMensajeUnidadtablet
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $mensaje_id
 * @property string $id_device
 * @property timestamp $fecha
 * @property integer $estado
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method integer             getMensajeId()  Returns the current record's "mensaje_id" value
 * @method string              getIdDevice()   Returns the current record's "id_device" value
 * @method timestamp           getFecha()      Returns the current record's "fecha" value
 * @method integer             getEstado()     Returns the current record's "estado" value
 * @method MensajeUnidadtablet setId()         Sets the current record's "id" value
 * @method MensajeUnidadtablet setMensajeId()  Sets the current record's "mensaje_id" value
 * @method MensajeUnidadtablet setIdDevice()   Sets the current record's "id_device" value
 * @method MensajeUnidadtablet setFecha()      Sets the current record's "fecha" value
 * @method MensajeUnidadtablet setEstado()     Sets the current record's "estado" value
 * 
 * @package    sistem-taxi
 * @subpackage model
 * @author     Walter Rosales
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMensajeUnidadtablet extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mensaje_unidadtablet');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('mensaje_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('id_device', 'string', 50, array(
             'type' => 'string',
             'fixed' => 1,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('fecha', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('estado', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}