<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('AsignacionUnidadPiloto', 'doctrine');

/**
 * BaseAsignacionUnidadPiloto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $id_piloto
 * @property string $descripcion
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property integer $created_by
 * @property integer $updated_by
 * @property integer $unidad_id
 * @property Piloto $Piloto
 * @property Unidad $Unidad
 * 
 * @method integer                getId()          Returns the current record's "id" value
 * @method integer                getIdPiloto()    Returns the current record's "id_piloto" value
 * @method string                 getDescripcion() Returns the current record's "descripcion" value
 * @method timestamp              getCreatedAt()   Returns the current record's "created_at" value
 * @method timestamp              getUpdatedAt()   Returns the current record's "updated_at" value
 * @method integer                getCreatedBy()   Returns the current record's "created_by" value
 * @method integer                getUpdatedBy()   Returns the current record's "updated_by" value
 * @method integer                getUnidadId()    Returns the current record's "unidad_id" value
 * @method Piloto                 getPiloto()      Returns the current record's "Piloto" value
 * @method Unidad                 getUnidad()      Returns the current record's "Unidad" value
 * @method AsignacionUnidadPiloto setId()          Sets the current record's "id" value
 * @method AsignacionUnidadPiloto setIdPiloto()    Sets the current record's "id_piloto" value
 * @method AsignacionUnidadPiloto setDescripcion() Sets the current record's "descripcion" value
 * @method AsignacionUnidadPiloto setCreatedAt()   Sets the current record's "created_at" value
 * @method AsignacionUnidadPiloto setUpdatedAt()   Sets the current record's "updated_at" value
 * @method AsignacionUnidadPiloto setCreatedBy()   Sets the current record's "created_by" value
 * @method AsignacionUnidadPiloto setUpdatedBy()   Sets the current record's "updated_by" value
 * @method AsignacionUnidadPiloto setUnidadId()    Sets the current record's "unidad_id" value
 * @method AsignacionUnidadPiloto setPiloto()      Sets the current record's "Piloto" value
 * @method AsignacionUnidadPiloto setUnidad()      Sets the current record's "Unidad" value
 * 
 * @package    sistem-taxi
 * @subpackage model
 * @author     Walter Rosales
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAsignacionUnidadPiloto extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('asignacion_unidad_piloto');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('id_piloto', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('descripcion', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('created_by', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('updated_by', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('unidad_id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Piloto', array(
             'local' => 'id_piloto',
             'foreign' => 'id'));

        $this->hasOne('Unidad', array(
             'local' => 'unidad_id',
             'foreign' => 'id'));
    }
}