<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Smilies', 'doctrine');

/**
 * BaseSmilies
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $image_code
 * @property string $path
 * 
 * @method integer getId()         Returns the current record's "id" value
 * @method string  getImageCode()  Returns the current record's "image_code" value
 * @method string  getPath()       Returns the current record's "path" value
 * @method Smilies setId()         Sets the current record's "id" value
 * @method Smilies setImageCode()  Sets the current record's "image_code" value
 * @method Smilies setPath()       Sets the current record's "path" value
 * 
 * @package    sistem-taxi
 * @subpackage model
 * @author     Walter Rosales
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSmilies extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('smilies');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('image_code', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
        $this->hasColumn('path', 'string', 100, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}