<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Trafia', 'doctrine');

/**
 * BaseTrafia
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property integer $created_by
 * @property integer $update_by
 * @property Doctrine_Collection $UnidadMensaje
 * @property Doctrine_Collection $UnidadMensaje_2
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method string              getName()            Returns the current record's "name" value
 * @method timestamp           getCreatedAt()       Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()       Returns the current record's "updated_at" value
 * @method integer             getCreatedBy()       Returns the current record's "created_by" value
 * @method integer             getUpdateBy()        Returns the current record's "update_by" value
 * @method Doctrine_Collection getUnidadMensaje()   Returns the current record's "UnidadMensaje" collection
 * @method Doctrine_Collection getUnidadMensaje2()  Returns the current record's "UnidadMensaje_2" collection
 * @method Trafia              setId()              Sets the current record's "id" value
 * @method Trafia              setName()            Sets the current record's "name" value
 * @method Trafia              setCreatedAt()       Sets the current record's "created_at" value
 * @method Trafia              setUpdatedAt()       Sets the current record's "updated_at" value
 * @method Trafia              setCreatedBy()       Sets the current record's "created_by" value
 * @method Trafia              setUpdateBy()        Sets the current record's "update_by" value
 * @method Trafia              setUnidadMensaje()   Sets the current record's "UnidadMensaje" collection
 * @method Trafia              setUnidadMensaje2()  Sets the current record's "UnidadMensaje_2" collection
 * 
 * @package    sistem-taxi
 * @subpackage model
 * @author     Walter Rosales
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTrafia extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('trafia');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => true,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 50,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 25,
             ));
        $this->hasColumn('created_by', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
        $this->hasColumn('update_by', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('UnidadMensaje', array(
             'local' => 'id',
             'foreign' => 'id_unidad'));

        $this->hasMany('UnidadMensaje as UnidadMensaje_2', array(
             'local' => 'id',
             'foreign' => 'id_tarifa'));
    }
}