generator:
  class: sfDoctrineGenerator
  param:
    model_class:           unidad
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          unidad
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields: ~
      list:
        title: Lista de Unidades
        hide: [id_marca,created_at,tipo_id,placa,anio_id,placa,linea_id,telefono]
      filter:
        class: false
      form:    ~
      edit:
        title: Modificacion de unidad
      new:
        title: Agregar nueva unidad
        
