<?php

/**
 * RutaCorporativaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RutaCorporativaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RutaCorporativaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RutaCorporativa');
    }
}