<?php

/**
 * AsignacionUnidadPiloto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sistem-taxi
 * @subpackage model
 * @author     Walter Rosales
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class AsignacionUnidadPiloto extends BaseAsignacionUnidadPiloto
{
	  public function namepiloto($id){

    	$piloto = Doctrine::getTable('piloto')->find($id);
    	return $piloto[0]->getFirstName();

    }
	  
	  public function obtenerpiloto($id){
		
		$q = Doctrine::getTable('asignacionUnidadPiloto')->findByUnidadId($id);
	   echo $q[0]->getPiloto()->getFirstName()." ".$q[0]->getPiloto()->getLastName();
		
	}
	  public function obtenerplaca($id){
		
		$q = Doctrine::getTable('asignacionUnidadPiloto')->findByUnidadId($id);
	   echo $q[0]->getUnidad()->getPlaca();
		
	}
	  
	 public function obtenerestado($id){
		
		$q = Doctrine::getTable('unidad')->findById($id);
		
	   if( $q[0]->getEstado() == 0 )
	     echo "FUERA DE SERVICIO";
	   if( $q[0]->getEstado() == 1 )
	     echo "LIBRE";
	   if( $q[0]->getEstado() == 2 )
	     echo "OCUPADO";
			
			
	} 
	  public function obtenertelefono($id){
		
		$q = Doctrine::getTable('asignacionUnidadPiloto')->findByUnidadId($id);
	   echo $q[0]->getPiloto()->getPhone();
		
	}
}
