<?php

/**
 * ChatTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ChatTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ChatTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Chat');
    }
}