<?php

/**
 * ClientChatTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClientChatTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClientChatTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ClientChat');
    }
}