<?php

/**
 * UnidadMensajeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EnvioUnidad extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EnvioUnidadTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EnvioUnidad');
    }
	public function mensajeUnidades($idunidad,$idservicio){
		
		//echo "DATOS: ".$idunidad." ".$idtarifa." ".$name." ".$origen." ".$destino." ".$telefono." ".$comment;	
		//exit;	
		   
		$mensaje = new envioUnidad();
		
		$mensaje->setUnidadId($idunidad);
		$mensaje->setServicioId($idservicio);
		$mensaje->setEstado(0);
		
		$mensaje->setUpdatedAt(date("Y-m-d H:i:s", (strtotime ("-2 Hours"))));
		$mensaje->setCreatedAt(date("Y-m-d H:i:s", (strtotime ("-2 Hours"))));
		$mensaje->save();
		
		   
		
		
	}
	
	public function serviciostomados(){
		
		$data = Doctrine::getTable('EnvioUnidad')
		      ->createQuery()
			  ->Where('estado = ?',1)
			  ->orderBy('id DESC')
			  ->limit(10)
              ->execute();
		return $data;	  
	}
}
	
}