<?php

/**
 * MapsTownsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MapsTownsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MapsTownsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MapsTowns');
    }
	public function OrdenarAscendente(){
		
		$result = doctrine::getTable('MapsTowns')
		                    ->createQuery('c')
			                ->orderBy('code ASC')
				           // ->AndWhere('c.state_id =?',$state_id)
			                ->execute();
			        return $result;
	}
}