<?php

/**
 * MensajeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MensajeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MensajeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Mensaje');
    }
}