<?php

/**
 * MensajeUnidadtabletTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MensajeUnidadtabletTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MensajeUnidadtabletTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MensajeUnidadtablet');
    }
}