<?php

/**
 * PilotoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PilotoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PilotoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Piloto');
    }
}