<?php

/**
 * ServicioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ServicioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ServicioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Servicio');
    }
	public function enviarMensajeUnidades($idunidad,$idtarifa,$name,$origen,$destino,$telefono,$comment){
		
		//echo "DATOS: ".$idunidad." ".$idtarifa." ".$name." ".$origen." ".$destino." ".$telefono." ".$comment;	
		//exit;	
		  
		$mensaje = new Servicio();
		
		$mensaje->setUnidadId(0);
		$mensaje->setTarifaId($idtarifa);
		$mensaje->setClientName($name);
		$mensaje->setClientOrigen($origen);
		$mensaje->setClientDestino($destino);
		$mensaje->setClientPhone($telefono);
		$mensaje->setDescription($comment);
		$mensaje->setEstado(0);
		$mensaje->setNotificacion(0);
		$mensaje->setCreatedAt(date("Y-m-d H:i:s", (strtotime ("-1 Hours"))));
		$mensaje->save();
		
		 return $mensaje->getId();  
		
		
	}
	
	public function serviciostomados(){
		
		$data = Doctrine::getTable('Servicio')
		      ->createQuery()
			  ->Where('estado = ?',1)
			  ->orderBy('id DESC')
			  ->limit(10)
              ->execute();
		return $data;	  
	}
	
	public function obtenercodigounidad($id){
		
		$data = Doctrine::getTable('Unidad')
		      ->createQuery()
			  ->Where('id = ?',$id)
			  ->execute();
		return $data[0]->getCodigo();
		
	}
}