<?php

/**
 * Tarifa
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    sistem-taxi
 * @subpackage model
 * @author     Walter Rosales
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Tarifa extends BaseTarifa
{
	
	public function obtenerTarifa($id){
		
		
		$q = Doctrine::getTable('Tarifa')->findById($id);
		echo $q[0]->getMonto();
	}
	
}