<?php

/**
 * UnidadMensajeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UnidadMensajeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UnidadMensajeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UnidadMensaje');
    }
	public function enviarMensajeUnidades($idunidad,$idtarifa,$name,$origen,$destino,$telefono,$comment){
		
		//echo "DATOS: ".$idunidad." ".$idtarifa." ".$name." ".$origen." ".$destino." ".$telefono." ".$comment;	
		//exit;	
		   
		$mensaje = new UnidadMensaje();
		
		$mensaje->setIdUnidad(0);
		$mensaje->setIdTarifa($idtarifa);
		$mensaje->setClientName($name);
		$mensaje->setClientOrigen($origen);
		$mensaje->setClientDestino($destino);
		$mensaje->setClientTelefono($telefono);
		$mensaje->setTexto($comment);
		$mensaje->setCreatedAt(date("Y-m-d H:i:s"));
		$mensaje->save();
		
		 return $mensaje->getId();  
		
		
	}
	
	public function serviciostomados(){
		
		$data = Doctrine::getTable('UnidadMensaje')
		      ->createQuery()
			  ->Where('estado = ?',1)
			  ->orderBy('id DESC')
			  ->limit(10)
              ->execute();
		return $data;	  
	}
}