<?php

/**
 * ViajeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ViajeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ViajeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Viaje');
    }
}